/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateProfileDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProfileDataAttributes{}

// CreateProfileDataAttributes struct for CreateProfileDataAttributes
type CreateProfileDataAttributes struct {
	// Username
	Username string `json:"username"`
	// Pseudonym
	Pseudonym *string `json:"pseudonym,omitempty"`
	// Description
	Description *string `json:"description,omitempty"`
}

type _CreateProfileDataAttributes CreateProfileDataAttributes

// NewCreateProfileDataAttributes instantiates a new CreateProfileDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProfileDataAttributes(username string) *CreateProfileDataAttributes {
	this := CreateProfileDataAttributes{}
	this.Username = username
	return &this
}

// NewCreateProfileDataAttributesWithDefaults instantiates a new CreateProfileDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProfileDataAttributesWithDefaults() *CreateProfileDataAttributes {
	this := CreateProfileDataAttributes{}
	return &this
}

// GetUsername returns the Username field value
func (o *CreateProfileDataAttributes) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *CreateProfileDataAttributes) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *CreateProfileDataAttributes) SetUsername(v string) {
	o.Username = v
}

// GetPseudonym returns the Pseudonym field value if set, zero value otherwise.
func (o *CreateProfileDataAttributes) GetPseudonym() string {
	if o == nil || IsNil(o.Pseudonym) {
		var ret string
		return ret
	}
	return *o.Pseudonym
}

// GetPseudonymOk returns a tuple with the Pseudonym field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProfileDataAttributes) GetPseudonymOk() (*string, bool) {
	if o == nil || IsNil(o.Pseudonym) {
		return nil, false
	}
	return o.Pseudonym, true
}

// HasPseudonym returns a boolean if a field has been set.
func (o *CreateProfileDataAttributes) HasPseudonym() bool {
	if o != nil && !IsNil(o.Pseudonym) {
		return true
	}

	return false
}

// SetPseudonym gets a reference to the given string and assigns it to the Pseudonym field.
func (o *CreateProfileDataAttributes) SetPseudonym(v string) {
	o.Pseudonym = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateProfileDataAttributes) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProfileDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateProfileDataAttributes) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateProfileDataAttributes) SetDescription(v string) {
	o.Description = &v
}

func (o CreateProfileDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProfileDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	if !IsNil(o.Pseudonym) {
		toSerialize["pseudonym"] = o.Pseudonym
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *CreateProfileDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProfileDataAttributes := _CreateProfileDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProfileDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateProfileDataAttributes(varCreateProfileDataAttributes)

	return err
}

type NullableCreateProfileDataAttributes struct {
	value *CreateProfileDataAttributes
	isSet bool
}

func (v NullableCreateProfileDataAttributes) Get() *CreateProfileDataAttributes {
	return v.value
}

func (v *NullableCreateProfileDataAttributes) Set(val *CreateProfileDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProfileDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProfileDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProfileDataAttributes(val *CreateProfileDataAttributes) *NullableCreateProfileDataAttributes {
	return &NullableCreateProfileDataAttributes{value: val, isSet: true}
}

func (v NullableCreateProfileDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProfileDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


