openapi: 3.0.0
info:
  title: Chains lab profile service
  description: profile service docs
  version: 0.0.1

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    #requests
    UpdateProfile:
      $ref: './spec/components/schemas/UpdateProfile.yaml'
    UpdateOfficial:
      $ref: './spec/components/schemas/UpdateOfficial.yaml'

    #responses
    Profile:
        $ref: './spec/components/schemas/Profile.yaml'
    ProfileData:
      $ref: './spec/components/schemas/ProfileData.yaml'
    ProfileAttributes:
      $ref: './spec/components/schemas/ProfileAttributes.yaml'
    ProfilesCollection:
      $ref: './spec/components/schemas/ProfilesCollection.yaml'

    PaginationData:
      $ref: './spec/components/schemas/PaginationData.yaml'