openapi: 3.1.1
info:
  title: NetBill profile service
  description: profile-svc docs
  version: 0.1.0

servers:
  - url: http://localhost:8002

paths:
  /profiles-svc/v1/profiles/:
    $ref: "./spec/paths/FilterProfiles.yaml"
  /profiles-svc/v1/profiles/u/{username}:
    $ref: "./spec/paths/ProfileByUsername.yaml"

  /profiles-svc/v1/profiles/me/:
    $ref: "./spec/paths/MyProfile.yaml"

  /profiles-svc/v1/profiles/{account_id}:
    $ref: "./spec/paths/ProfileByID.yaml"
  /profiles-svc/v1/profiles/{account_id}/official:
    $ref: "./spec/paths/ProfileOfficial.yaml"


components:
  schemas:
    #requests
    CreateProfile:
      $ref: './spec/components/schemas/requests/CreateProfile.yaml'
    UpdateProfile:
      $ref: './spec/components/schemas/requests/UpdateProfile.yaml'
    UpdateProfileOfficial:
      $ref: './spec/components/schemas/requests/UpdateProfileOfficial.yaml'

    #responses
    Profile:
      $ref: './spec/components/schemas/responses/Profile.yaml'
    ProfileData:
      $ref: './spec/components/schemas/responses/ProfileData.yaml'
    ProfileAttributes:
      $ref: './spec/components/schemas/responses/ProfileAttributes.yaml'
    ProfilesCollection:
      $ref: './spec/components/schemas/responses/ProfilesCollection.yaml'

    Errors:
      $ref: './spec/components/schemas/responses/Errors.yaml'
    PaginationData:
      $ref: './spec/components/schemas/responses/PaginationData.yaml'